<html>
<head>
<title>Détail de la correction.</title>
<style>
p.titre {font-weight: bold; font-family: Arial; font-size: 14pt;}
span.titreTest {font-weight: bold; font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.verdictTest {font-family: Arial; font-size: 12pt;}
span.titreException {font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.titreMessage {font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.titrePileAppel {font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.titreDiagnostic {font-family: Arial; font-size: 12pt; font-style: italic; color: #3300CC;}
span.pileAppel {font-family: Arial; font-size: 11pt;}
</style>
</head>
<body>
<p class="titre">Voici les tests qui ont posé des problèmes à votre exécutable. Cette liste est vide si tous se sont déroulés sans incident.</p>
<p><span class="titreTest">testUpdateItem(F):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at F.a(Unknown Source)<br>	at F.testUpdateItem(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at K.tester(Unknown Source)<br>	at K.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testUpdateItem(F): null</span></p>
<br>
<p><span class="titreTest">testCreateCategory(V):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at V.a(Unknown Source)<br>	at V.testCreateCategory(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at K.tester(Unknown Source)<br>	at K.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testCreateCategory(V): null</span></p>
<br>
<p><span class="titreTest">testCreateItem(F):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at F.a(Unknown Source)<br>	at F.testCreateItem(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at K.tester(Unknown Source)<br>	at K.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testCreateItem(F): null</span></p>
<br>
<p><span class="titreTest">testUpdateProduct(g):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at g.a(Unknown Source)<br>	at g.testUpdateProduct(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at K.tester(Unknown Source)<br>	at K.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testUpdateProduct(g): null</span></p>
<br>
<p><span class="titreTest">testCreateProduct(g):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at g.a(Unknown Source)<br>	at g.testCreateProduct(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at K.tester(Unknown Source)<br>	at K.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testCreateProduct(g): null</span></p>
<br>
<p><span class="titreTest">testUpdateCategory(V):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at V.a(Unknown Source)<br>	at V.testUpdateCategory(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at K.tester(Unknown Source)<br>	at K.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testUpdateCategory(V): null</span></p>
<br>
</body>
</html>
